name: Auto merge
on: pull_request
jobs:
  merge:
    if: ${{ github.actor == 'dependabot[bot]' }} # Dependabot の PR のみ
    runs-on: ubuntu-latest
    permissions: # マージに必要なパーミッション
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Github CLI のクレデンシャル
    steps:
      - uses: actions/checkout@v5
      - run: gh pr merge "${GITHUB_HEAD_REF}" --merge # Github CLI でマージ
